### ISSUE TITLE
add to README cc/gfortran related info

### ISSUE THREAD

**Issue by davydden** [tjhei/dealii-brew#1]
not really an issue, but some extra notes. 
To use system's `gcc` and `gfortran` you may need to do something like

```
prefix=~/.linuxbrew
ln -s /apps/gcc/4.8.2/bin/gcc $prefix/bin/gcc-4.8
ln -s /apps/gcc/4.8.2/bin/g++ $prefix/bin/g++-4.8
ln -s /apps/gcc/4.8.2/bin/gfortran $prefix/bin/gfortran-4.8
export HOMEBREW_CC=gcc-4.8
export FC=gfortran-4.8
brew tap homebrew/versions
```

the last line is needed because there are some internal checks in `linuxbrew` to be able to fallback to specific versions of `gcc`, but it won't install anything. `export FC` is needed as it is clear from https://github.com/davydden/linuxbrew/blob/master/Library/Homebrew/requirements/fortran_requirement.rb (unless you have `gfortran` in path).

`clang` may work out-of-the-box, but `icc` would need to have `linuxbrew` modified, in particular this file https://github.com/Homebrew/linuxbrew/blob/master/Library/Homebrew/compilers.rb and something else, i suppose...

**Comment by tjhei** [comment]
Thanks.

> To use system's gcc and gfortran you may need to do something like

Strange, it worked for me without doing this so far. Maybe because g++,gfortran, etc. are in my path?

> clang may work out-of-the-box, but icc would need to have linuxbrew modified

Yeah, I am not too worried about intel right now.

**Comment by tjhei** [comment]
Oh, what is the correct way to tell homebrew what compilers/mpi-wrappers to use and how can I use that in a formula?

**Comment by davydden** [comment]
i hope the way above is the correct one for things which don't need mpi. It solved some issues Bruno had recently.

Otherwise as long as you have mpi in the path (or OpenMP installed in linuxbrew with the compilers specified as above), and a formula has `depends_on :mpi => [:cc, :cxx, :fortran]` (or something like this), it should be picked up by https://github.com/davydden/linuxbrew/blob/master/Library/Homebrew/requirements/mpi_requirement.rb

**Comment by tjhei** [comment]
So it is hardcoded to use mpicc, mpicxx, mpif77, mpif90? I see that you also just hardcode these compilers in dealii.rb. Ideally mpi_requirement would export variables for the compilers and dealii uses those. We'll need this to support intel.

**Comment by davydden** [comment]
yes, i think it's hardcoded. Perhaps an easier workaround would be to symlink intel compilers to `mpixyz`.  Some tests in formulae may fail if intel has arguments different from `mpirun -np X executable`.
